name: 🔨 Build & Test

on:
  workflow_dispatch:
  pull_request:

jobs:

  build:
    name: 🔨 Build & Test
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Make gradle executable
        run: chmod +x ./gradlew

      - name: Build with gradle
        run: ./gradlew build --stacktrace

      - name: Execute unit tests
        run: ./gradlew test --stacktrace

      - name: Upload test report
        uses: actions/upload-artifact@v3
        with:
          name: ktlint report
          path: shared/build/reports/ktlint/ktlintCommonMainSourceSetCheck/